added rx filter
Proftit-TC/coding-steps pull request #39
Opened 2021-05-20 18:26 UTC by abrl91

issue: https://github.com/Proftit-TC/coding-steps/issues/10

2021-05-20 20:22 UTC, elpddev requested changes
Excellent! Thank you. I've fixed my typo bug in main so related imports can be changed back. 

Regarding the warning of `changeset`. You can run `yarn changeset` and answer which package was changed. That will create a file that can be committed to the repo. It will help with the release and bumping automatically the package version.

2021-05-20 20:22 UTC, elpddev commented on packages/rxjs-from-the-ground-up/src/create-observable/create-observable.ts
> +  const observable = {
Looks great. This file is for function signature only which need to be empty. The real solution can be moved to the `./solutions` folder.

2021-05-20 20:22 UTC, elpddev commented on packages/rxjs-from-the-ground-up/src/create-observable/solutions/create-observable.solution.starosaur.ts
> +import { TeardownLogic } from "../../types/treadown-logic";
I've fixed my typo bug in main so this can be changed back.

2021-05-21 08:48 UTC, abrl91 commented on packages/rxjs-from-the-ground-up/src/create-observable/create-observable.ts
>  import { TeardownLogic } from "../types/treadown-logic";
haha  I have taken your solution in the meantime because I have not yet been able to come up with my own working solution

2021-05-21 08:51 UTC, abrl91 commented on packages/rxjs-from-the-ground-up/src/create-observable/create-observable.ts
> +  const observable = {
Makes sense

2021-05-21 13:19 UTC, elpddev approved these changes

2021-05-21 13:21 UTC, merged